#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     joystick_left,  sensorTouch)
#pragma config(Sensor, S3,     joystick_right, sensorTouch)
#pragma config(Sensor, S4,     soma,           sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	robotType();
	while (true)
  {
    switch (SensorValue[joystick_left])
    {
    case true:
      startMotor(mtr_S1_C1_2, -100);
      startMotor(mtr_S1_C2_2, -100);
      break;

    default:
      stopMotor(mtr_S1_C1_2);
      stopMotor(mtr_S1_C2_2);
    }
    switch (SensorValue[joystick_right])
    {
    case true:
      startMotor(mtr_S1_C1_1, 100);
      startMotor(mtr_S1_C2_1, 100);
      break;

    default:
      stopMotor(mtr_S1_C1_1);
      stopMotor(mtr_S1_C2_1);
    }
    switch (SensorValue[soma]<25)
    {
    case true:
      PlaySound(soundFastUpwardTones);
      break;
    }
  }
}
